[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py migrate --noinput && python manage.py collectstatic --noinput && python manage.py seed_data && python manage.py auto_create_admin && gunicorn tracker.wsgi --bind 0.0.0.0:$PORT"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
